//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTable
    {
        public int Category_ID { get; set; }
        public string Category_Nmae { get; set; }
        public string Category_Image { get; set; }
        public string Category_Description { get; set; }
    }
}
