//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public string Order_ID { get; set; }
        public int Order_No { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Order_Total { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> Shipping_Date { get; set; }
        public string Is_Delivered { get; set; }
    }
}
