//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_DetailsTable
    {
        public int Order_Details_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Product_Qty { get; set; }
        public Nullable<int> Product_Price { get; set; }
        public string Order_ID { get; set; }
        public Nullable<int> Subtotal { get; set; }
    }
}
