//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Prodecut_Desc { get; set; }
        public string Image_1 { get; set; }
        public string Image_2 { get; set; }
        public string Image_3 { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public int Category_ID { get; set; }
    }
}
